name: Posix

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Enable no password for sudo
        run: |
          sudo sed -i '' 's/%admin		ALL = (ALL) ALL/%admin		ALL = (ALL) NOPASSWD: ALL/g' /etc/sudoers
          sudo -v
    - name: Install libiscsi-dev
      run: sudo apt-get -y install libiscsi-dev
    - name: cmake
      run: cmake -B build
    - name: make
      run: make -C build
