name: Posix

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name:  Install libiscsi-dev
      run: sudo apt-get -y install libiscsi-dev
    - name: cmake
      run: cmake -B build
    - name: make
      run: make -C build
